### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by antoney1998** [curtacircuitos/pcb-tools#151]
(pcb_test) C:\Python37-32\internsh\pcb-tools\examples>python cairo_example.py
Traceback (most recent call last):
  File "cairo_example.py", line 63, in <module>
    ctx.dump(os.path.join(os.path.dirname(__file__), 'cairo_example.png'))
  File "C:\Python37-32\internsh\pcb_test\lib\site-packages\pcb_tools-0.1-py3.7.egg\gerber\render\cairo_backend.py", line 150, in dump
  File "C:\Python37-32\internsh\pcb_test\lib\site-packages\cairocffi\surfaces.py", line 597, in write_to_png
    self._pointer, _encode_filename(target)))
  File "C:\Python37-32\internsh\pcb_test\lib\site-packages\cairocffi\__init__.py", line 69, in _check_status
    raise exception(message, status)
MemoryError: ("cairo returned CAIRO_STATUS_NO_MEMORY: b'out of memory'", 1)

**Comment by antoney1998** [comment]
I get this error while running the example file

This line throws error

ctx.dump(os.path.join(os.path.dirname(__file__), 'cairo_example.png'))
