### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by greenscreenflicker** [curtacircuitos/pcb-tools#72]
I followed the installation steps. However the example fails.

michael@oldgrey:~/work/pcb-tools/examples$ python render_gerbv_tests.py 
Loaded Gerber file: test-aperture-circle-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-image-rotation-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-knockout-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-image-polarity-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-aperture-polygon-flash-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-step-and_repeat-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-aperture-polygon-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-scale-factor-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-image-offset-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-aperture-rectangle-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-rotation-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-polygon-fill-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Excellon file: test-drill-trailing-zero-1.exc
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-image-justify-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-image-justify-2.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-aperture-obround-flash-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-circular-interpolation-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-aperture-rectangle-flash-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-include-file-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-step-and_repeat-2.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-aperture-obround-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-mode-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-aperture-circle-flash-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-mirror-image-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Excellon file: test-drill-leading-zero-1.exc
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-knockout-2.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Excellon file: test-drill-repeat-1.exc
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-axis-select-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-image-offset-2.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments
Loaded Gerber file: test-layer-offset-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 274, in render
    ctx._paint_background()
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 579, in _paint_background
    self.output_ctx.set_source_rgba(*color, alpha=alpha)
TypeError: set_source_rgba() takes no keyword arguments

How to fix?

**Comment by greenscreenflicker** [comment]
@curtacircuitos

**Comment by hamiltonkibbe** [comment]
This should be fixed by f7a719e6f7 can you try again with the latest version

**Comment by greenscreenflicker** [comment]
@hamiltonkibbe 
I'm afraid not all fixed.

michael@oldgrey:~/work/pcb-tools/examples$ python cairo_example.py 
Traceback (most recent call last):
  File "cairo_example.py", line 44, in <module>
    ctx.render_layer(copper)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 98, in render_layer
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 198, in _render_layer
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 154, in render
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 363, in _render_rectangle
TypeError: rectangle() takes no keyword arguments


michael@oldgrey:~/work/pcb-tools/examples$ python render_gerbv_tests.py 
Loaded Gerber file: test-aperture-circle-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 148, in render
    self._render_arc(primitive, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 255, in _render_arc
    mask.ctx.arc(*center, radius=radius, angle1=angle1, angle2=angle2)
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-image-rotation-1.gbx
Writing output to: test-image-rotation-1.png
Loaded Gerber file: test-layer-knockout-1.gbx
Writing output to: test-layer-knockout-1.png
Loaded Gerber file: test-image-polarity-1.gbx
Writing output to: test-image-polarity-1.png
Loaded Gerber file: test-aperture-polygon-flash-1.gbx
Writing output to: test-aperture-polygon-flash-1.png
Loaded Gerber file: test-layer-step-and_repeat-1.gbx
Writing output to: test-layer-step-and_repeat-1.png
Loaded Gerber file: test-aperture-polygon-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 148, in render
    self._render_arc(primitive, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 255, in _render_arc
    mask.ctx.arc(*center, radius=radius, angle1=angle1, angle2=angle2)
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-layer-scale-factor-1.gbx
Writing output to: test-layer-scale-factor-1.png
Loaded Gerber file: test-image-offset-1.gbx
Writing output to: test-image-offset-1.png
Loaded Gerber file: test-aperture-rectangle-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 148, in render
    self._render_arc(primitive, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 255, in _render_arc
    mask.ctx.arc(*center, radius=radius, angle1=angle1, angle2=angle2)
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-layer-rotation-1.gbx
Writing output to: test-layer-rotation-1.png
Loaded Gerber file: test-polygon-fill-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 150, in render
    self._render_region(primitive, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 295, in _render_region
    angle1=angle1, angle2=angle2)
TypeError: arc() takes no keyword arguments
Loaded Excellon file: test-drill-trailing-zero-1.exc
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 160, in render
    self._render_drill(primitive, self.color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 510, in _render_drill
    self._render_circle(circle, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 315, in _render_circle
    angle2=(2 * math.pi))
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-image-justify-1.gbx
Writing output to: test-image-justify-1.png
Loaded Gerber file: test-image-justify-2.gbx
Writing output to: test-image-justify-2.png
Loaded Gerber file: test-aperture-obround-flash-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 156, in render
    self._render_obround(primitive, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 412, in _render_obround
    angle2=(2 * math.pi))
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-circular-interpolation-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 148, in render
    self._render_arc(primitive, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 255, in _render_arc
    mask.ctx.arc(*center, radius=radius, angle1=angle1, angle2=angle2)
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-aperture-rectangle-flash-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 154, in render
    self._render_rectangle(primitive, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 363, in _render_rectangle
    mask.ctx.rectangle(*lower_left, width=width, height=height)
TypeError: rectangle() takes no keyword arguments
Loaded Gerber file: test-include-file-1.gbx
Writing output to: test-include-file-1.png
Loaded Gerber file: test-layer-step-and_repeat-2.gbx
Writing output to: test-layer-step-and_repeat-2.png
Loaded Gerber file: test-aperture-obround-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 148, in render
    self._render_arc(primitive, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 255, in _render_arc
    mask.ctx.arc(*center, radius=radius, angle1=angle1, angle2=angle2)
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-layer-mode-1.gbx
Writing output to: test-layer-mode-1.png
Loaded Gerber file: test-aperture-circle-flash-1.gbx
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 152, in render
    self._render_circle(primitive, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 315, in _render_circle
    angle2=(2 * math.pi))
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-layer-mirror-image-1.gbx
Writing output to: test-layer-mirror-image-1.png
Loaded Excellon file: test-drill-leading-zero-1.exc
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 160, in render
    self._render_drill(primitive, self.color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 510, in _render_drill
    self._render_circle(circle, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 315, in _render_circle
    angle2=(2 * math.pi))
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-layer-knockout-2.gbx
Writing output to: test-layer-knockout-2.png
Loaded Excellon file: test-drill-repeat-1.exc
Traceback (most recent call last):
  File "render_gerbv_tests.py", line 52, in <module>
    layer.render(ctx)
  File "build/bdist.linux-x86_64/egg/gerber/cam.py", line 278, in render
    ctx.render(p)
  File "build/bdist.linux-x86_64/egg/gerber/render/render.py", line 160, in render
    self._render_drill(primitive, self.color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 510, in _render_drill
    self._render_circle(circle, color)
  File "build/bdist.linux-x86_64/egg/gerber/render/cairo_backend.py", line 315, in _render_circle
    angle2=(2 * math.pi))
TypeError: arc() takes no keyword arguments
Loaded Gerber file: test-layer-axis-select-1.gbx
Writing output to: test-layer-axis-select-1.png
Loaded Gerber file: test-image-offset-2.gbx
Writing output to: test-image-offset-2.png
Loaded Gerber file: test-layer-offset-1.gbx
Writing output to: test-layer-offset-1.png

**Comment by hamiltonkibbe** [comment]
removed the rest of the instances of mixing unpacks with kwargs... Let me know if that fixes it for you.
